# Generated by Django 4.2.2 on 2023-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
