# Generated by Django 4.2.2 on 2023-06-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
