# Generated by Django 4.2.2 on 2023-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='codigo_de_barras',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
