# Generated by Django 4.2.2 on 2023-07-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_situacao'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nome_produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
