# Generated by Django 4.2.2 on 2023-07-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacoesestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoesestoque',
            name='data_hora',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimentacoesestoque',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='nome_produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque'),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
