# Generated by Django 4.2.2 on 2023-07-11 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_categoria'),
        ('estoque', '0004_movimentacoesestoque_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='data_hora',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='nome_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
