# Generated by Django 4.2.2 on 2023-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_de_barras', models.CharField(max_length=20, unique=True)),
                ('preco', models.FloatField()),
                ('situacao', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('alimento', 'Alimento'), ('vestuario', 'Vestuário'), ('cinema', 'Ingresso')], max_length=20)),
            ],
        ),
    ]
