# Generated by Django 4.2.2 on 2023-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(default=123456789101234, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
