# Generated by Django 4.2.2 on 2023-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_codigo_de_barras_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
