# Generated by Django 4.2.2 on 2023-07-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
