# Generated by Django 4.2.2 on 2023-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('vestuario', 'Vestuário'), ('eletronico', 'Eletrônico')], default='Alimento', max_length=20),
        ),
    ]
