# Generated by Django 4.2.2 on 2023-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('vestuario', 'Vestuário'), ('cinema', 'Ingresso')], default='Alimento', max_length=20),
        ),
    ]
