# Generated by Django 4.2.2 on 2023-07-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('vestuario', 'Vestuário'), ('cinema', 'Ingresso')], max_length=20),
        ),
    ]
