# Generated by Django 4.2.2 on 2023-06-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_produto_preco'),
        ('colaboradores', '0003_colaborador_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField()),
                ('colab_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_individual', models.FloatField()),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.registrocompra')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
    ]
