# Generated by Django 4.2.2 on 2023-06-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_preco'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcompra',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='compra_id',
        ),
        migrations.RemoveField(
            model_name='registrocompra',
            name='produto_id',
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.registrocompra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='produtos',
            field=models.ManyToManyField(through='compras.ItemCompra', to='produtos.produto'),
        ),
    ]
